//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.23 at 03:42:22 PM IST 
//


package com.studup.model.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accreditationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="accreditationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="percentage" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="cgpaMax" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="cgpaReceived" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="cgpaOrPercentageHide" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="depttRank" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="depttRankHide" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="classRank" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="classRankHide" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accreditationType")
public class AccreditationType {

    @XmlAttribute(name = "id")
    protected Integer id;
    @XmlAttribute(name = "percentage")
    protected Integer percentage;
    @XmlAttribute(name = "cgpaMax")
    protected Integer cgpaMax;
    @XmlAttribute(name = "cgpaReceived")
    protected Integer cgpaReceived;
    @XmlAttribute(name = "cgpaOrPercentageHide")
    protected Boolean cgpaOrPercentageHide;
    @XmlAttribute(name = "depttRank")
    protected Integer depttRank;
    @XmlAttribute(name = "depttRankHide")
    protected Boolean depttRankHide;
    @XmlAttribute(name = "classRank")
    protected Integer classRank;
    @XmlAttribute(name = "classRankHide")
    protected Boolean classRankHide;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the percentage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPercentage() {
        return percentage;
    }

    /**
     * Sets the value of the percentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPercentage(Integer value) {
        this.percentage = value;
    }

    /**
     * Gets the value of the cgpaMax property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCgpaMax() {
        return cgpaMax;
    }

    /**
     * Sets the value of the cgpaMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCgpaMax(Integer value) {
        this.cgpaMax = value;
    }

    /**
     * Gets the value of the cgpaReceived property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCgpaReceived() {
        return cgpaReceived;
    }

    /**
     * Sets the value of the cgpaReceived property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCgpaReceived(Integer value) {
        this.cgpaReceived = value;
    }

    /**
     * Gets the value of the cgpaOrPercentageHide property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCgpaOrPercentageHide() {
        return cgpaOrPercentageHide;
    }

    /**
     * Sets the value of the cgpaOrPercentageHide property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCgpaOrPercentageHide(Boolean value) {
        this.cgpaOrPercentageHide = value;
    }

    /**
     * Gets the value of the depttRank property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDepttRank() {
        return depttRank;
    }

    /**
     * Sets the value of the depttRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDepttRank(Integer value) {
        this.depttRank = value;
    }

    /**
     * Gets the value of the depttRankHide property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDepttRankHide() {
        return depttRankHide;
    }

    /**
     * Sets the value of the depttRankHide property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDepttRankHide(Boolean value) {
        this.depttRankHide = value;
    }

    /**
     * Gets the value of the classRank property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getClassRank() {
        return classRank;
    }

    /**
     * Sets the value of the classRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setClassRank(Integer value) {
        this.classRank = value;
    }

    /**
     * Gets the value of the classRankHide property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isClassRankHide() {
        return classRankHide;
    }

    /**
     * Sets the value of the classRankHide property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setClassRankHide(Boolean value) {
        this.classRankHide = value;
    }

}
