//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.23 at 03:42:22 PM IST 
//


package com.studup.model.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for marksheetSubjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="marksheetSubjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="marksheet" type="{http://www.example.org/Student}marksheetType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="earnedgrade" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="marksreceived" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "marksheetSubjectType", propOrder = {
    "marksheet"
})
public class MarksheetSubjectType {

    @XmlElement(required = true)
    protected MarksheetType marksheet;
    @XmlAttribute(name = "id")
    protected Integer id;
    @XmlAttribute(name = "earnedgrade")
    protected String earnedgrade;
    @XmlAttribute(name = "marksreceived")
    protected Integer marksreceived;

    /**
     * Gets the value of the marksheet property.
     * 
     * @return
     *     possible object is
     *     {@link MarksheetType }
     *     
     */
    public MarksheetType getMarksheet() {
        return marksheet;
    }

    /**
     * Sets the value of the marksheet property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarksheetType }
     *     
     */
    public void setMarksheet(MarksheetType value) {
        this.marksheet = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the earnedgrade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEarnedgrade() {
        return earnedgrade;
    }

    /**
     * Sets the value of the earnedgrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEarnedgrade(String value) {
        this.earnedgrade = value;
    }

    /**
     * Gets the value of the marksreceived property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMarksreceived() {
        return marksreceived;
    }

    /**
     * Sets the value of the marksreceived property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMarksreceived(Integer value) {
        this.marksreceived = value;
    }

}
