//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.23 at 03:42:22 PM IST 
//


package com.studup.model.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.studup.model.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Student_QNAME = new QName("http://www.example.org/Student", "Student");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.studup.model.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StudentType }
     * 
     */
    public StudentType createStudentType() {
        return new StudentType();
    }

    /**
     * Create an instance of {@link SemesterYearType }
     * 
     */
    public SemesterYearType createSemesterYearType() {
        return new SemesterYearType();
    }

    /**
     * Create an instance of {@link DegreeType }
     * 
     */
    public DegreeType createDegreeType() {
        return new DegreeType();
    }

    /**
     * Create an instance of {@link SubjectDetailType }
     * 
     */
    public SubjectDetailType createSubjectDetailType() {
        return new SubjectDetailType();
    }

    /**
     * Create an instance of {@link AccreditationType }
     * 
     */
    public AccreditationType createAccreditationType() {
        return new AccreditationType();
    }

    /**
     * Create an instance of {@link MarksheetType }
     * 
     */
    public MarksheetType createMarksheetType() {
        return new MarksheetType();
    }

    /**
     * Create an instance of {@link UniversityCollegeType }
     * 
     */
    public UniversityCollegeType createUniversityCollegeType() {
        return new UniversityCollegeType();
    }

    /**
     * Create an instance of {@link MarksheetSubjectType }
     * 
     */
    public MarksheetSubjectType createMarksheetSubjectType() {
        return new MarksheetSubjectType();
    }

    /**
     * Create an instance of {@link DepartmentType }
     * 
     */
    public DepartmentType createDepartmentType() {
        return new DepartmentType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StudentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Student", name = "Student")
    public JAXBElement<StudentType> createStudent(StudentType value) {
        return new JAXBElement<StudentType>(_Student_QNAME, StudentType.class, null, value);
    }

}
