//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.23 at 03:42:22 PM IST 
//


package com.studup.model.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for subjectDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="subjectDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="marksheetSubject" type="{http://www.example.org/Student}marksheetSubjectType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="marksmax" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="subjcode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subjname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subjtag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "subjectDetailType", propOrder = {
    "marksheetSubject"
})
public class SubjectDetailType {

    @XmlElement(required = true)
    protected List<MarksheetSubjectType> marksheetSubject;
    @XmlAttribute(name = "id")
    protected Integer id;
    @XmlAttribute(name = "marksmax")
    protected Integer marksmax;
    @XmlAttribute(name = "subjcode")
    protected String subjcode;
    @XmlAttribute(name = "subjname")
    protected String subjname;
    @XmlAttribute(name = "subjtag")
    protected String subjtag;

    /**
     * Gets the value of the marksheetSubject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the marksheetSubject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarksheetSubject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MarksheetSubjectType }
     * 
     * 
     */
    public List<MarksheetSubjectType> getMarksheetSubject() {
        if (marksheetSubject == null) {
            marksheetSubject = new ArrayList<MarksheetSubjectType>();
        }
        return this.marksheetSubject;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the marksmax property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMarksmax() {
        return marksmax;
    }

    /**
     * Sets the value of the marksmax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMarksmax(Integer value) {
        this.marksmax = value;
    }

    /**
     * Gets the value of the subjcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjcode() {
        return subjcode;
    }

    /**
     * Sets the value of the subjcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjcode(String value) {
        this.subjcode = value;
    }

    /**
     * Gets the value of the subjname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjname() {
        return subjname;
    }

    /**
     * Sets the value of the subjname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjname(String value) {
        this.subjname = value;
    }

    /**
     * Gets the value of the subjtag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjtag() {
        return subjtag;
    }

    /**
     * Sets the value of the subjtag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjtag(String value) {
        this.subjtag = value;
    }

}
