CREATE UNIQUE INDEX student_uq ON student (email_id);


INSERT INTO university_college VALUES(1,'RCCIIT');
INSERT INTO university_college VALUES(2,'HVI');


INSERT INTO DEPARTMENT VALUES(1,'IT',1);
INSERT INTO DEPARTMENT VALUES(2,'CS',1);
INSERT INTO DEPARTMENT VALUES(3,'ECE',1);
INSERT INTO DEPARTMENT VALUES(4,'SCIENCE',2);
INSERT INTO DEPARTMENT VALUES(5,'ARTS',2);
INSERT INTO DEPARTMENT VALUES(6,'COMMERCE',2);


INSERT INTO DEGREE VALUES(1,'B.TECH',1);
INSERT INTO DEGREE VALUES(2,'M.TECH',1);
INSERT INTO DEGREE VALUES(3,'B.TECH',2);
INSERT INTO DEGREE VALUES(4,'M.TECH',2);
INSERT INTO DEGREE VALUES(5,'B.TECH',3);
INSERT INTO DEGREE VALUES(6,'M.TECH',3);
INSERT INTO DEGREE VALUES(7,'HSC',4);
INSERT INTO DEGREE VALUES(8,'HSC',5);
INSERT INTO DEGREE VALUES(9,'HSC',6);